name: UpdateDockerHubMetadata

on:
  push:
    branches:
    - master

jobs:
  update_docker_hub_metadata:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update Docker hub metadata
      uses: docker://mpepping/docker-hub-metadata-github-action
      env:
        name: tomfrench/liquidityburner
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
